apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zk8g4jula-go
  janus-idp.io/tekton: zk8g4jula-go
  backstage.io/kubernetes-id: zk8g4jula-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zk8g4jula-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
